pwquality_generate(): Don't report CrackLib errors as 'low entropy'
If the CrackLib dictionaries were missing, pwmake(1) would complain that
the entropy is too low:
  $ pwmake 64
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  Error: Password generation failed - required entropy too low for
    settings

... and confuse users [1].

This changes it to report something closer to the truth:
  $ pwmake 64
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
  Error: The password fails the dictionary check

... so that users can help themselves by installing the CrackLib
dictionaries.

[1] https://github.com/containers/toolbox/issues/1351