Fix the error in handling the return value of the pwquality_generate function
The commit aeff47d had changed the return value of pwquality_generate().
Now, the positive return value is the score of the password, not the error.
Fix the issue like this:
$ pwmake 64
Error: Unknown error

Signed-off-by: yixiangzhike <yixiangzhike007@163.com>